# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmyservice\"3\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05par_1\x18\x02 \x01(\x03\x12\r\n\x05par_2\x18\x03 \x01(\x03\"H\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05par_1\x18\x02 \x01(\x03\x12\r\n\x05par_2\x18\x03 \x01(\x03\x12\x12\n\ngcd_result\x18\x04 \x01(\x03\x32\x44\n\tMyService\x12\x37\n\nComputeGCD\x12\x12.myservice.Request\x1a\x13.myservice.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=28
  _REQUEST._serialized_end=79
  _RESPONSE._serialized_start=81
  _RESPONSE._serialized_end=153
  _MYSERVICE._serialized_start=155
  _MYSERVICE._serialized_end=223
# @@protoc_insertion_point(module_scope)
